Fix issue with new line added and beginning of file that starts with a tag.
Medology/gherkin-cs-fixer pull request #39
Opened 2021-07-19 22:45 UTC by aserv92

For: Medology/www.healthlabs.com/issues/1604

Before:
Notice: Begins with a new line and two spaces
```gherkin

  @skipapi @sandbox
Feature: Find a Lab
  In order to place my order
  As a customer
  I need to be able to pick a lab

  Background:
    Given there is a geocoded Quest lab

  Scenario Outline: Lab can be selected by zip code
    Given I am on "/find-a-lab"
     Then I should see "Enter Your Zip Code"
...
```

After:
```gherkin
@skipapi @sandbox
Feature: Find a Lab
  In order to place my order
  As a customer
  I need to be able to pick a lab

  Background:
    Given there is a geocoded Quest lab

  Scenario Outline: Lab can be selected by zip code
    Given I am on "/find-a-lab"
     Then I should see "Enter Your Zip Code"
...
```

2021-07-20 17:24 UTC, johnnie502 approved these changes

2021-07-21 15:38 UTC, fortoulrodolfo requested changes

2021-07-21 15:38 UTC, fortoulrodolfo commented on src/Application.php
> +        $this->previousStepDto = null;
Why does need to be null if everything else is create with an object?

2021-07-21 15:53 UTC, aserv92 commented on src/Application.php
> +        $this->previousStepDto = null;
The other 5 objects are created and used over and over again. The `previousStepDto ` attribute is overwritten at the end of every iteration. Also, if the step currently being worked on is the first line then there is no `previousStepDto`. If the `previousStepDto` is initialized and has a keyword of `None`(which is the default), that is interpreted as the last line was empty, but also the `previousStepDto` may not exist.

2021-07-21 15:55 UTC, fortoulrodolfo commented on src/Application.php
> +        $this->previousStepDto = null;
That makes much more sense now. Please update the PR description with this explanation of your changes

2021-07-21 15:58 UTC, fortoulrodolfo requested changes

2021-07-21 15:58 UTC, fortoulrodolfo commented on src/Fixers/NoneStepFixer.php
> +    public function run(?StepDto $previousStepDto): string
you are passing this object to this method but later is not used at all?? 🤔

2021-07-21 15:58 UTC, fortoulrodolfo commented on src/Fixers/StepFixer.php
> +    public function run(?StepDto $previousStepDto): string
Same here.

2021-07-21 15:58 UTC, fortoulrodolfo commented on src/Fixers/TagStepFixer.php
> +        return parent::run($previousStepDto);
why you need to pass it to the parent if later wont use it???

2021-07-21 15:58 UTC, fortoulrodolfo commented on tests/Fixers/TagFixer/RunTest.php
> +        $previousStepDto = null;
Can you please add gherkin sentence to follow you test??

2021-07-21 16:02 UTC, aserv92 commented on src/Fixers/NoneStepFixer.php
> +    public function run(?StepDto $previousStepDto): string
All of the run signatures have to match otherwise a PHP fatal error will occur. This is because they all extend from `\Medology\GherkinCsFixer\Fixers\StepFixer`

2021-07-21 16:03 UTC, aserv92 commented on src/Fixers/StepFixer.php
> +    public function run(?StepDto $previousStepDto): string
All of the run signatures have to match otherwise a PHP fatal error will occur. Other fixers extend this class

2021-07-21 16:03 UTC, aserv92 commented on src/Fixers/TagStepFixer.php
> +        return parent::run($previousStepDto);
All of the run signatures have to match otherwise a PHP fatal error will occur. This is because they all extend from `\Medology\GherkinCsFixer\Fixers\StepFixer`

2021-07-21 16:04 UTC, aserv92 commented on src/Fixers/TagStepFixer.php
> +        return parent::run($previousStepDto);
Should I create a fixer interface to resolve these problems?

2021-07-22 13:06 UTC, fortoulrodolfo approved these changes

2021-07-22 13:07 UTC, fortoulrodolfo requested changes

2021-07-22 13:07 UTC, fortoulrodolfo commented on src/Fixers/NoneStepFixer.php
> +
this is not in used

2021-07-22 13:07 UTC, fortoulrodolfo commented on src/Fixers/TagStepFixer.php
> +
no in used

2021-07-22 17:40 UTC, fortoulrodolfo approved these changes

2021-07-22 18:44 UTC, manuerumx approved these changes
I don't understand anything about the project, but I trust you @aserv92  😄

2021-07-23 11:14 UTC, rashidsaf approved these changes

2021-07-23 15:34 UTC, merged